### PR TITLE
Added auto update feature; changed installation process; reflected back in README  

### PR DESCRIPTION
**Pull request by clearnote01**

### CODE REVIEW

**Comment by Akarshit** [comment]
@clearnote01 You can keep making changes to your previous commit using `git commit --amend`. Read more about that [here](https://www.atlassian.com/git/tutorials/rewriting-history/). This would help you merge the commit messages(like `minor md fixes`, `some md fixes`, `some more md fixes`, `md is annoying... more fixes`) into one.

You can still do the same using git squash. Read about it and try to make this PR's history clean.

**Comment by clearnote01** [comment]
I don't have a md viewer and so i was commiting to see how it looks on github. i'll see what an do, i don't want to mess the content. (btw, md is completely moronic, double-spaces to go to next line? who thinks like that)

**Comment by Akarshit** [comment]
Even after you commit and you have made the changes, you can merge that changes in the previous commit using `git commit --amend` and then force push the branch on github using `git push origin +HEAD`

**Comment by clearnote01** [comment]
Meh, i did so many stupid things... you need not see the mess I made. git reflog is god.

**Pull request merged**
